In [2]:
import pandas as pd

In [3]:
notes = pd.DataFrame([[6.5,6.8,5.8,7.9,8.8,'Barcelona'], [6.8,7.0,6.5,8.9,9.2,'Girona'],
                                                [7.8,6.2,6.5,4.1,8.0,'Tarragona'], [6.9,7.2,4.7,8.8,6.2,'Lleida']],
                                                columns=['Història','Matemàtiques','Física','Anglès','Biologia',
                                               'Ciutat'],index=['Joan','Laura','Enric','Georgina',])

In [4]:
notes

          Història  Matemàtiques  Física  Anglès  Biologia     Ciutat
Joan           6.5           6.8     5.8     7.9       8.8  Barcelona
Laura          6.8           7.0     6.5     8.9       9.2     Girona
Enric          7.8           6.2     6.5     4.1       8.0  Tarragona
Georgina       6.9           7.2     4.7     8.8       6.2     Lleida

In [10]:
print(notes['Física']['Laura'])
print(notes['Ciutat']['Joan'])

6.5
Barcelona

In [11]:
notes[notes.Física > 5]

       Història  Matemàtiques  Física  Anglès  Biologia     Ciutat
Joan        6.5           6.8     5.8     7.9       8.8  Barcelona
Laura       6.8           7.0     6.5     8.9       9.2     Girona
Enric       7.8           6.2     6.5     4.1       8.0  Tarragona

In [14]:
# notes['Física']['Georgina'] = 8 #Da warning
notes.loc['Georgina','Física'] = 9
notes

          Història  Matemàtiques  Física  Anglès  Biologia     Ciutat
Joan           6.5           6.8     5.8     7.9       8.8  Barcelona
Laura          6.8           7.0     6.5     8.9       9.2     Girona
Enric          7.8           6.2     6.5     4.1       8.0  Tarragona
Georgina       6.9           7.2     9.0     8.8       6.2     Lleida

In [15]:
notes.loc[['Laura','Georgina'],['Biologia', 'Ciutat']]

          Biologia  Ciutat
Laura          9.2  Girona
Georgina       6.2  Lleida

In [16]:
mitjanes = []
desviacio = []
for i in range(4):
    mitjana = notes.iloc[i, 0:5].mean()
    desv = notes.iloc[i, 0:5].std()
    mitjanes.append(mitjana)
    desviacio.append(desv)
notes['Mitjanes'] = mitjanes
notes['Desviació'] = desviacio
notes

,Història,Matemàtiques,Física,Anglès,Biologia,Ciutat,Mitjanes,Desviació
Joan,6.5,6.8,5.8,7.9,8.8,Barcelona,7.16,1.188697
Laura,6.8,7.0,6.5,8.9,9.2,Girona,7.68,1.267675
Enric,7.8,6.2,6.5,4.1,8.0,Tarragona,6.52,1.564289
Georgina,6.9,7.2,9.0,8.8,6.2,Lleida,7.62,1.225561